{{- if .Values.aws.createSecretStore }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.aws.secretStore.name }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.secretStoreSpec.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.aws.secretStoreSpec.authSecret.name }}
            key: {{ .Values.aws.secretStoreSpec.authSecret.accessKeyIDKey }}
          secretAccessKeySecretRef:
            name: {{ .Values.aws.secretStoreSpec.authSecret.name }}
            key: {{ .Values.aws.secretStoreSpec.authSecret.secretAccessKeyKey }}
{{- end }}
