{{- if .Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.name }}-restricted
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.name }}
{{- if .Values.networkPolicy.ingressRules }}
  ingress:
{{- range .Values.networkPolicy.ingressRules }}
{{ toYaml (list .) | nindent 4 }}
{{- end }}
{{- end }}
{{- if .Values.networkPolicy.egressRules }}
  egress:
{{- range .Values.networkPolicy.egressRules }}
{{ toYaml (list .) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
