apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.name }}-sa"
  namespace: {{ .Values.namespace }}