{{- $argocdNamespace := default "argocd" .Values.argocd.namespace -}}
{{- $vclusterName := .Values.vcluster_config.name -}}
{{- $vclusterNamespace := .Values.vcluster_config.namespace -}}
{{- $serviceAccountName := printf "eso-reader-%s" $vclusterName -}}
{{- $clusterRoleName := printf "eso-read-vcluster-secrets-%s" $vclusterName -}}
{{- $clusterRoleBindingName := printf "%s-binding" $clusterRoleName -}}
{{- $secretStoreName := printf "%s-vcluster-reader" $vclusterName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $argocdNamespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $clusterRoleName }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vc-{{ $vclusterName }}"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $clusterRoleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $argocdNamespace }}

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $secretStoreName }}
  namespace: {{ $argocdNamespace }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $vclusterNamespace }}
      auth:
        serviceAccount:
          name: {{ $serviceAccountName }}
      server:
        url: "https://kubernetes.default.svc.cluster.local"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ $vclusterName }}-cluster-es"
  namespace: {{ $argocdNamespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: SecretStore
  target:
    name: "{{ $vclusterName }}-cluster"
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: "{{ $vclusterName }}"
        server: "https://{{ $vclusterName }}.{{ $vclusterNamespace }}.svc.cluster.local"
        config: |
          {
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ `{{ .ca | b64enc }}` }}",
              "certData": "{{ `{{ .clientCert | b64enc }}` }}",
              "keyData": "{{ `{{ .clientKey | b64enc }}` }}"
            }
          }
  data:
  - secretKey: ca
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: vc-{{ $vclusterName }}
      property: certificate-authority
  - secretKey: clientCert
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: vc-{{ $vclusterName }}
      property: client-certificate
  - secretKey: clientKey
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: vc-{{ $vclusterName }}
      property: client-key