apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-reader
  namespace: argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-read-vcluster-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vc-vcluster-a"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-read-vcluster-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-read-vcluster-secrets
subjects:
  - kind: ServiceAccount
    name: eso-reader
    namespace: argocd

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vcluster-reader
  namespace: argocd
spec:
  provider:
    kubernetes:
      remoteNamespace: vcluster-a
      auth:
        serviceAccount:
          name: eso-reader
      server:
        url: "https://kubernetes.default.svc.cluster.local"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.vcluster_config.name }}-es"
  namespace: argocd  # Target
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vcluster-reader
    kind: SecretStore
  target:
    name: "{{ .Values.vcluster_config.name }}-secret"  # Secret name in target NS
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: "{{ .Values.vcluster_config.name }}"
        server: "https://{{ .Values.vcluster_config.name }}.{{ .Values.vcluster_config.namespace }}.svc.cluster.local"
        config: |
          {
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ `{{ .ca | b64enc }}` }}",
              "certData": "{{ `{{ .clientCert | b64enc }}` }}",
              "keyData": "{{ `{{ .clientKey | b64enc }}` }}"
            }
          }
  data:
  - secretKey: ca
    remoteRef:
      key: vc-{{ .Values.vcluster_config.name }}
      property: certificate-authority
  - secretKey: clientCert
    remoteRef:
      key: vc-{{ .Values.vcluster_config.name }}
      property: client-certificate
  - secretKey: clientKey
    remoteRef:
      key: vc-{{ .Values.vcluster_config.name }}
      property: client-key