apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.name }}
  ingress:
    - fromEntities:
        - all
      toPorts:
        - ports:
            - port: "{{ .Values.servicePort }}"
              protocol: TCP
