name: service
namespace: service
image: ghcr.io/your-org/service:latest
replicas: 1
port: 80
extraServicePorts: []
env: {}
ingress:
  enabled: false
  hostname: "example.s8-hetzner.online"
  environment: staging
