enabled: true

policy:
  namePrefix: tenant-shared

frontend:
  namespace: tenant-one
  labels:
    app.kubernetes.io/name: frontend
  serviceAccount: frontend

backend:
  namespace: shared-services
  labels:
    app.kubernetes.io/name: backend
  serviceName: backend
  port: 80
  protocol: TCP

clusterIdentity:
  allowedRemoteCluster: eks-auto

authentication:
  mode: required

hubble:
  enabled: true
