apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/service
    helm:
      valuesObject:
        name: auth-service
        namespace: auth-service
        image: ghcr.io/mario26rgl/auth-service:281aae56e64a6622196ce0c9f2c689f747d847bc
        replicas: 2
        port: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        autoscaling:
          hpa:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
          vpa:
            enabled: true
            updateMode: Auto
            controlledValues: RequestsAndLimits
            minAllowed:
              cpu: 50m
              memory: 64Mi
            maxAllowed:
              cpu: 500m
              memory: 512Mi
        env:
          DSN: host=postgres.postgres.svc.cluster.local user=postgres password=password dbname=users port=5432 sslmode=disable TimeZone=UTC connect_timeout=5
          LOGGER_SERVICE_URL: http://logger-service.logger-service.svc.cluster.local
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-service
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
