apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/service
    helm:
      valuesObject:
        name: frontend
        namespace: frontend
        image: ghcr.io/mario26rgl/front-end:07f7c79eabbb299fc88c20193f6ef71dd10c4b9a
        replicas: 1
        port: 80
        ingress:
          enabled: true
          hostname: "app.s8-hetzner.online"
          # environment: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
