apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/service
    helm:
      valuesObject:
        name: frontend
        namespace: frontend
        image: ghcr.io/mario26rgl/front-end:b7b9fa6200793267273afa137de5c8e2598b5bc1
        replicas: 2
        port: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        autoscaling:
          hpa:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
          vpa:
            enabled: true
            updateMode: Auto
            controlledValues: RequestsAndLimits
            minAllowed:
              cpu: 50m
              memory: 64Mi
            maxAllowed:
              cpu: 500m
              memory: 512Mi
        ingress:
          enabled: true
          hostname: "app.s8-hetzner.online"
          # environment: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
