apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listener-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/service
    helm:
      valuesObject:
        name: listener-service
        namespace: listener-service
        image: ghcr.io/mario26rgl/listener-service@sha256:56150da7c7c377f97dbbc8f12df6d5da5bc2077905a92272af013b359a47b8de
        replicas: 2
        port: 2112
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        autoscaling:
          hpa:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
          vpa:
            enabled: true
            updateMode: Auto
            controlledValues: RequestsAndLimits
            minAllowed:
              cpu: 50m
              memory: 64Mi
            maxAllowed:
              cpu: 500m
              memory: 512Mi
        env:
          RABBITMQ_URL: amqp://user:password@rabbitmq.rabbitmq.svc.cluster.local:5672/
          LOGGER_SERVICE_URL: http://logger-service.logger-service.svc.cluster.local
          LOGGER_SERVICE_RPC_ADDR: logger-service.logger-service.svc.cluster.local:5001
  destination:
    server: https://kubernetes.default.svc
    namespace: listener-service
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
