apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logger-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/service
    helm:
      valuesObject:
        name: logger-service
        namespace: logger-service
        image: ghcr.io/mario26rgl/logger-service:0814107a1bc04d699d5b567cc90b129045dac6f7
        replicas: 2
        port: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        autoscaling:
          hpa:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
          vpa:
            enabled: true
            updateMode: Auto
            controlledValues: RequestsAndLimits
            minAllowed:
              cpu: 50m
              memory: 64Mi
            maxAllowed:
              cpu: 500m
              memory: 512Mi
        extraServicePorts:
          - name: rpc
            port: 5001
            targetPort: 5001
          - name: grpc
            port: 50051
            targetPort: 50051
        env:
          MONGO_URL: mongodb://mongo.mongo.svc.cluster.local:27017
  destination:
    server: https://kubernetes.default.svc
    namespace: logger-service
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
