apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/database
    helm:
      valuesObject:
        name: postgres
        namespace: postgres
        image: postgres:14.2
        replicas: 1
        servicePort: 5432
        containerPort: 5432
        env:
          PGDATA: /var/lib/postgresql/data/pgdata
        secret:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: users
        persistence:
          enabled: true
          size: 5Gi
          mountPath: /var/lib/postgresql/data
        bootstrap:
          enabled: true
          statePath: /var/lib/postgresql/data/.users-bootstrap.sha256
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
