apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-access
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mario26rgl/s8-hetzner-kubernetes.git'
    targetRevision: main
    path: kubernetes/argocd-tenant-rbac
    helm:
      valueFiles:
        - ../tenants/tenants.yaml
      values: |
        argocdNamespace: argocd
        aws:
          createSecretStore: true
          secretStore:
            name: aws-secretsmanager
            kind: SecretStore
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
